### ISSUE TITLE
the syntax [] (empty square brackets) causes an error

### ISSUE THREAD

**Issue by yannickbattail** [hugheaves/scadformat#1]
the following code cause the error: `ERROR syntax error on line 1:3 - no viable alternative at input '[]'`
```scad
b = [];
```

the following code cause the error: `ERROR   syntax error on line 1:15 - mismatched input '?' expecting ';'`
```scad
a = x?[0]:[];
```

**Comment by hugheaves** [comment]
@yannickbattail , thanks very much for reporting this, and even more, contributing a fix and README updates. Very much appreciated!

Hugh
