### ISSUE TITLE
Minor documentation suggestions V0.6

### ISSUE THREAD

**Issue by FreeWilly2022** [hugheaves/scadformat#14]
Again thanks for putting this together, I have a large scad project that was a mess with a lot of files, and this cleaned it up quick and easy.

But I thought you might like to know about a minor issue I found compiling, the directions are to enter:
go build -o scadformat cmd/main.go

but actually the file name is different, and this is the command that worked:
go build -o scadformat cmd/scadformat.go

Also, to recursively reformat all the files in a directory, would this be a better suggestion (reference the scadformat directory)?
find . -type f -name "*.scad" -exec ~/scadformat/scadformat "{}" \;

**Comment by hugheaves** [comment]
Good catch. Forgot to update the doc after I renamed the file.

I've also added some more info to the doc about the "scadformat" command when using find.
