### ISSUE TITLE
Minor editorial suggestions

### ISSUE THREAD

**Issue by FreeWilly2022** [hugheaves/scadformat#8]
Thanks for putting this together. I had to build a version for my linux arm64 and found these minor issues in the ReadMe.md:
Under Building, Checkout source code, remove the semicolon after https:;

Next I had to change the scadformat directory permissions by:
sudo chmod 0777 -R ./scadformat

Of course using 0777 permissions is a no-no, so if you know what permissions are needed, please substitute.

Otherwise it compiled and works nicely, thanks again!

**Comment by hugheaves** [comment]
Thanks for letting me know. I'll fix after the holidays! You've also got me interested to see if I can coerce github Actions into cross-compiling an ARM64 binary.

**Comment by yannickbattail** [comment]
I fix the typo in the readme
https://github.com/hugheaves/scadformat/pull/9

**Comment by hugheaves** [comment]
Created https://github.com/hugheaves/scadformat/issues/10 for providing ARM64 binaries.

**Comment by hugheaves** [comment]
Fixed via https://github.com/hugheaves/scadformat/pull/9
